### ISSUE TITLE
 Error parsing event data

### ISSUE THREAD

**Issue by mask0t** [pusher/libPusher#100]
Hello, sorry for my English/
I Have a some problem with libPusher
When i try to receive push event

[chl bindToEventNamed:@"msg" handleWithBlock:^(PTPusherEvent *channelEvent) {
         NSLog(@"chat %@",channelEvent.data);
}];

in the output i watch 
[pusher] Error parsing event data (not JSON?)

and i watch this

chat "{\"uid\":\"96613\",\"login\":\"micronick\",\"msg\":\"Axelandr76, \\u0442\\u0430\\u043a \\u0435\\u043b\\u0435\\u043a\\u0442\\u0440\\u043e \\u043f\\u043e\\u0442\\u0440\\u0435\\u0431\\u043b\\u0435\\u043d\\u0438\\u044f \\u0442\\u043e\\u0436\\u0435 \\u0431\\u0443\\u0434\\u0435\\u0442 \\u0432\\u043e\\u0437\\u0440\\u043e\\u0441\\u0442\\u0430\\u0442\\u044c \\u0430 \\u0437\\u0430 \\u0435\\u043b\\u0435\\u043a\\u0442\\u0440\\u0438\\u0447\\u0435\\u0441\\u0442\\u0432\\u043e \\u043d\\u0435 \\u0434\\u0435\\u0448\\u043e\\u0432\\u043e\\u0435... \\u0449\\u044f\\u0441 \\u0433\\u0434\\u0435\\u0442\\u043e 30% \\u043e\\u0442 \\u0434\\u043e\\u0445\\u043e\\u0434\\u0430 \\u0438\\u0434\\u0435\\u0442 \\u043d\\u0430 \\u043e\\u043f\\u043b\\u0430\\u0442\\u0443\",\"msg_id\":4885784,\"date\":\"05.06.13 12:02:27\",\"usr_clr\":\"#8da0b9\"}"

why JSON do not parsed?

**Comment by hamchapman** [comment]
I've tried with Cyrillic characters, emoji, all sorts, and haven't been able to get a parsing error so closing this for now.

**Comment by DannyBlok** [comment]
Hi i have the same issue.
Somethimes i only return a NSString form Server.
In the PTPusherEvent.m

If my event data is like this @"/"StringValue/""
It always comes in

      if (_data == nil) {
        NSLog(@"[pusher] Error parsing event data (not JSON?)");
        _data = [data copy];
      }

The stringValue that's returning is correct. 
But i want to know why it shows the Log error.
Your doc in the .h says it can be a simple string
