### ISSUE TITLE
-[PTPusherEventDispatcher addEventListenerForEventNamed:block:queue:]: unrecognized selector sent to instance 0xb0bd090

### ISSUE THREAD

**Issue by jkmassel** [pusher/libPusher#109]
Seems the static library and the headers disagree on what this call actually is

5    *\*  
PTPusherChannel.m line 136
-[PTPusherChannel bindToEventNamed:handleWithBlock:queue:]
6    *\* 
PTPusherChannel.m line 131
-[PTPusherChannel bindToEventNamed:handleWithBlock:]
7    *\* 
PTPusherChannel.m line 63
-[PTPusherChannel initWithName:pusher:]
8    *\* 
PTPusherChannel.m line 42
+[PTPusherChannel channelWithName:pusher:]
9    *\* 
PTPusher.m line 164
-[PTPusher subscribeToChannelNamed:]

PTPusherEventDispatcher says: - (PTPusherEventBinding *)addEventListener:(id<PTEventListener>)listener forEventNamed:(NSString *)eventName;

**Comment by daemeh** [comment]
I had the same problem, I fixed it by adding -all_load to 'Other linker flags'
