### ISSUE TITLE
Private Channel Authorization Block instead of forcing HTTP request

### ISSUE THREAD

**Issue by zldavis** [pusher/libPusher#155]
It would be great to have an optional authorization block for private channels so that we could provide the client an authorization token that we have received in some other means, other then always forcing each subscription request to make an individual HTTP request to retrieve a token.

For example, if we were continually subscribing to multiple channels, it would be great to be able to receive authorization tokens in batch to improve performance and reduce the number of outbound network requests required.  Or, in some case, we may want to return authorization tokens with other requests (say initial login request/response) to also save on the number of requests required.

Something in the delegate, say:
```
- (void)pusher:(PTPusher *)pusher authorizeChannel:(PTPusherChannel *)channel withBlock:(NSDictionary (^)())authorization;
```

**Comment by lukeredpath** [comment]
This will be available in 1.7, see #213 which will be merged shortly.
