### ISSUE TITLE
PTPusherPresenceChannel memberRemoved has error

### ISSUE THREAD

**Issue by finalevil** [pusher/libPusher#175]
Hi,

I use the PTPusherPresenceChannel. And set the delegate for memberAdded and memberRemoved.
memberAdded works fine.

But when the memberRemoved trigger. the member parameter always nil.

I put the unsubscribe code like this

```
- (void)viewWillDisappear:(BOOL)animated
{
    [super viewWillDisappear:animated];
    
    [appDelegate.presenceChannel unsubscribe];
    [appDelegate.pusherClient disconnect];
    
    appDelegate.presenceChannel = nil;
    appDelegate.pusherClient = nil;
    
}
```

It has any wrong about leave the channel?

Thank you very much.

**Comment by mitchymitch** [comment]
I also have this issue. An ugly work around is just to query the members property before and after the add/remove events arrive to deduce who actually left. Thats what I had to do.

**Comment by finalevil** [comment]
@mitchymitch  ok, thanks. I will try it : )
