### ISSUE TITLE
PTPusher does not have a member named subscribeToPresenceChannelNamed

### ISSUE THREAD

**Issue by waclock** [pusher/libPusher#184]
I have the following code in one of my controllers:

        //Pusher
        client = PTPusher.pusherWithKey("285f2959b454140783d7", delegate: self, encrypted:false) as! PTPusher
        client.authorizationURL = NSURL(string: appDelegate.base_url+"/api/pusher/auth?access_token="+appDelegate.user!.accessToken!)

        client.connect()

        println("Connecting to channel: conversation-" + appDelegate.current_conversation!.conversationID!.description)
        
        var channel = client.subscribeToPresenceChannelNamed("conversation-"+appDelegate.current_conversation!.conversationID!.description)

At first it was working with cocoapods, however cocoapods isn't working with iOS7, which is why I had to add the library manually. Now subscribeToPresenceChannelNamed is not recognized as a method of the client.

**Comment by hamchapman** [comment]
This shouldn't be occurring whether using Cocoapods or not. I've tried to recreate it but couldn't. If this is still a relevant issue, please reopen 👍
