### ISSUE TITLE
NSURLConnection deprecation warning in iOS 9

### ISSUE THREAD

**Issue by hamchapman** [pusher/libPusher#188]
`initWithRequest:delegate:startImmediately` is deprecated in iOS 9. Need to change to using NSURLSession instead.

![screen shot 2015-09-21 at 10 48 47](https://cloud.githubusercontent.com/assets/2475150/9989214/936c3742-604e-11e5-9c22-6f4f168e76c2.png)

**Comment by lukeredpath** [comment]
@hamchapman I've been thinking about the idea of removing the Pusher REST API wrapper from the library, perhaps extracting to a new library instead. Is there a reason why a client would need to send events this way instead of using socket based events?

**Comment by hamchapman** [comment]
I'm sure some people do use it to do that, but with the ability to send client events then there shouldn't be a need to. Extracting interaction with the straight HTTP API into a separate library would also mean that people's app secrets shouldn't need to be included in apps that people build, which is certainly a good idea! 

I've let people use the secret in the Swift library but that's really there just for testing so that you don't need to setup an auth endpoint to get things up and running. Ideally you'd never include your secret in an actual app release.

That's a long-winded way of me saying that what you suggested sounds like a great idea! :+1:

**Comment by leggetter** [comment]
+1

**Comment by lukeredpath** [comment]
Further discussion in #189

**Comment by hamchapman** [comment]
#213 has been merged and this is now fixed
