### ISSUE TITLE
Header files not found during pod spec lint

### ISSUE THREAD

**Issue by yellokrow** [pusher/libPusher#203]
I have noticed that when running pod spec lint, the podspec clones the repo and when compiling, the headers cannot be found. I see that the scheme used is Release, can the scheme not be changed to something else to see if I could resolve this issue?

**Comment by hamchapman** [comment]
Hi @yellokrow I can't seem to recreate this. This is the output I get when running `pod spec lint`:

```
 pod spec lint

 -> libPusher (1.6.1)

Analyzed 1 podspec.

libPusher.podspec passed validation.
```

**Comment by hamchapman** [comment]
Couldn't recreate myself so closing for now
