### ISSUE TITLE
Exposing state property

### ISSUE THREAD

**Issue by scottfister** [pusher/libPusher#214]
We recently updated to `use_frameworks!` and one of the errors that cropped up was that the `PTPushConnection`'s `state` property wasn't exposed.

I know there's a getter for whether it's connected. 

The `PTPusherConnectionState` enum is still exposed, leading me to wonder why `state` is not?

I've made a fork of this exposing the property for our use, but wondering what you recommend here long-term?

**Comment by lukeredpath** [comment]
Can you elaborate on the error you were encountering?

The state property is definitely not intended to be exposed or be part of the public API in any way.

**Comment by hamchapman** [comment]
@scottfister Just to reiterate what Luke asked, can you provide more info on the error that appeared in relation to the `state` property? 

Would be much appreciated!

**Comment by hamchapman** [comment]
Closing as stale
