### ISSUE TITLE
Update podfile on Cocoapods trunk to get new dependences

### ISSUE THREAD

**Issue by dral3x** [pusher/libPusher#224]
I notice that the current podfile is different from the one published on cocoapods repo
https://github.com/pusher/libPusher/blob/master/libPusher.podspec
https://github.com/CocoaPods/Specs/blob/master/Specs/libPusher/1.6.1/libPusher.podspec.json

I think you should release these changes as a minor new version (1.6.2) so that the bugs related to SocketRocket (reconnect on clean disconnect) will be fixed.

There is any reason why not to do this?
Thank you so much!

**Comment by hamchapman** [comment]
@dral3x we are planning on doing a minor release (1.7) very soon

It likely won't include the push-notifications code (as that's still a beta product feature) but will include the fixes you described.

Stay tuned

**Comment by dral3x** [comment]
Thanks for the clarification.

In the meantime, I will fetch the pod directly from the master repo
`pod 'libPusher', :git => 'https://github.com/pusher/libPusher.git'`

Looking forward to the 1.7 release!
