### ISSUE TITLE
Optional PTPusherDelegate Methods Aren't Optional

### ISSUE THREAD

**Issue by emcmanus** [pusher/libPusher#228]
PTPusherDelegate's push notification methods aren't implemented to be optional, e.g.:

https://github.com/pusher/libPusher/blob/push-notifications/Library/PTNativePusher.m#L90

**Comment by hamchapman** [comment]
This should be fixed by https://github.com/pusher/libPusher/commit/12dabe18fdba62071838961d79652188c41654cc
