### ISSUE TITLE
Ship 1.6.2 to fix warnings

### ISSUE THREAD

**Issue by keith** [pusher/libPusher#229]
New with Xcode 8 SocketRocket produces some warnings about unused results of functions:

![screen shot 2016-08-29 at 11 48 01](https://cloud.githubusercontent.com/assets/283886/18063095/72e35944-6dde-11e6-83a0-3db5cfc071f4.png)

This has been fixed in SocketRocket (at least by version 0.5.1). It also seems that, on master, SocketRocket has [been updated](https://github.com/pusher/libPusher/blob/1635beb97a986a82cdc3e7052f1aef14c41ef01c/libPusher.podspec#L17) to this new version, but since this update, there hasn't been a new version of libPusher.

Is it possible to ship a new 1.6.2 release so that this warning is fixed?

Thanks!

**Comment by hamchapman** [comment]
I should be able to get a release done on Monday.

Sorry about the delay - I've been away and unable to get a release done.

**Comment by keith** [comment]
Thanks!!


--
Keith Smiley

**Comment by hamchapman** [comment]
1.6.2 has been pushed to cocoapods master 👍

**Comment by keith** [comment]
Ah it turns out SocketRocket hasn't shipped a release since fixing these warnings either. So I guess it'll have to be the next time around.

**Comment by hamchapman** [comment]
I've asked about a potential release of SocketRocket here: https://github.com/facebook/SocketRocket/issues/466

Will publish a new version of libPusher if / when SocketRocket has a new release

**Comment by keith** [comment]
Thanks!


--
Keith Smiley
