### ISSUE TITLE
No auth data sent in subscription event

### ISSUE THREAD

**Issue by sschendel** [pusher/libPusher#235]
PTPusherChannel subscribeWithAuthorization does not pass the auth data into event sent to subscribe.  This results in no check on auth signature.

The subscribeWithAuthorization method is passed auth data, but it is not used in event.

Looked into this when we noticed our Android client (which properly passes auth data in subscribe event) getting signature invalid errors but iOS client did not report same errors when subscribing to private channels.   

Our auth endpoint was not properly authorizing private channels (we authorized them as presence channels - therefore signature was not valid).

**Comment by hamchapman** [comment]
I'm not quite sure I understand what you're saying.

As far as I can tell, it looks like the auth data is getting passed in when making the subscription calls: https://github.com/pusher/libPusher/blob/1775fdb8fe97a821489dd35f7f49cbf6ebc2750c/Library/PTPusherChannel.m#L224-L234

Is this what you're referring to?

**Comment by sschendel** [comment]
I was mistaken looking at the parent implementation here: 
https://github.com/pusher/libPusher/blob/master/Library/PTPusherChannel.m#L169-L176

So it looks like auth data is passed in event as you mention for private channels.  

The scenario we are experiencing that I cannot explain...

Our implementation of auth endpoint currently authorizes private channels incorrectly.  They are authorized as presence channels.  i.e. calling Pusher.authenticate with channel data included.  https://pusher.com/docs/authenticating_users#implementing_presence_endpoints

Authorization works fine, but the auth data response includes a signature hashed with HMAC SHA256 including the channel data.  

https://pusher.com/docs/auth_signatures

Following authorization to this private channel (authorized incorrectly as presence channel)...

... our Android client errors with a response to subscribe event complaining about an invalid signature.  Our iOS client does not error and the channel subscription works fine with the invalid signature.

So I was wrong when jumping to conclusion seeing the parent PTPusherChannel subscribeWithAuthorization implementation, but still not quite sure why iOS client allows subscription with invalid signature.  Sorry for the confusion.

**Comment by hamchapman** [comment]
I think what it boils down to is how the two libraries handle sending the auth data. libPusher just sends whatever data it receives, which, if you're treating everything as a presence channel, means that it'll be sending some value (presumably empty) for the `channel_data` key, whereas pusher-websocket-java explicitly only sends the `channel` and `auth` values and excludes the `channel_data` key, even if it is returned: https://github.com/pusher/pusher-websocket-java/blob/master/src/main/java/com/pusher/client/channel/impl/PrivateChannelImpl.java#L87-L110.

As such, when the `auth` value is checked on the Pusher servers it will be expecting the `channel_data`, even if it is empty, so have formed part of the `auth` value, but it sees no `channel_data` from the Android subscribe calls, and so they fail.

If you change your server to not respond with any channel data (and make sure it's not set when the auth value is generated) then they subscription attempts from both sets of clients (iOS and Android) should be consistent in terms of whether they succeed or not.

Thanks!

**Comment by sschendel** [comment]
I see.  Makes sense.  Thanks for the explanation.
