### ISSUE TITLE
Push lib crashes

### ISSUE THREAD

**Issue by GigabyteTheOne** [pusher/libPusher#243]
Sometimes lib crashes the whole app when you trying to send 2 commands like this:

`[[_client nativePusher] registerWithDeviceToken:deviceToken];`
`[[_client nativePusher] subscribe:@"all"];`

Crash is on this line in PTNativePusher.m:
`[outbox removeObjectAtIndex:0];`

**Comment by hamchapman** [comment]
I imagine it's related to this: https://github.com/pusher/libPusher/issues/230

You can use [pusher-websocket-swift](https://github.com/pusher/pusher-websocket-swift) with either Swift or Objective-C and that has support for native push notifications (and no thread safety problems!)

**Comment by GigabyteTheOne** [comment]
I made a small fix, it works for me. Please check my pull request #244 :)

**Comment by hamchapman** [comment]
Merged #244
