### ISSUE TITLE
Retain cycle in PTURLRequestOperation

### ISSUE THREAD

**Issue by danset** [pusher/libPusher#245]
`NSURLSession` retains its delegate until you invalidate it which currently only happens when the operation is cancelled.  There needs to be a call to `finishTasksAndInvalidate` or `invalidateAndCancel` somewhere in the case where the operation finishes executing or it never gets deallocated since the operation and the session are retaining each other.

**Comment by rex-remind101** [comment]
Did this fix your issue https://github.com/pusher/libPusher/pull/246 ?

**Comment by lukeredpath** [comment]
Sounds like a dupe of #246 to me.
