### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by rex-remind101** [pusher/libPusher#252]
Hoping we can get a new cocoapods release that includes https://github.com/pusher/libPusher/pull/250 thanks!

**Comment by hamchapman** [comment]
I'll make a 1.6.3 release now

**Comment by hamchapman** [comment]
I ran into some issues with the tests failing when running on Travis, which then had a large backlog os OSX builds. I have a theory as to why the tests were failing which I'll be following up tomorrow. Apologies that I couldn't get a new release out today!

**Comment by rex-remind101** [comment]
No problem, thanks for looking into this :)

**Comment by hamchapman** [comment]
Got everything building successfully on Travis so 1.6.3 is now released 👍
