### ISSUE TITLE
Segfault on OS X

### ISSUE THREAD

**Issue by henrikhodne** [pusher/libPusher#51]
Hey,

Seems like libPusher segfaults on Snow Leopard. The full crash report can be found here: travis-ci/travis-watcher-macosx#3.

Seems like this could be caused by an instance of SRWebSocket not being retained. Looking at [the code](https://github.com/lukeredpath/libPusher/blob/master/Library/PTPusherConnection.m#L64), it seems like the SRWebSocket instance is just being assigned to an instance variable, which to the best of my knowledge does not retain the instance. I'm not too familiar with Objective-C, though. Is there a reason this isn't assigned with a `@property` setter? I'd love to submit a pull request if it should be changed, but if it's actually supposed to be this way, then I won't.

**Comment by hamchapman** [comment]
Closing as stale and seems like it was related to an old version os OS X.
